### ISSUE TITLE
Cannot read property 'sessionId' of undefined

### ISSUE THREAD

**Issue by karneaud** [colyseus/colyseus#192]
on an `onLeave` handler event i trigger a `this.disconnect()` and I seem to be getting the following error

> TypeError: Cannot read property 'sessionId' of undefined
> 2018-11-04T22:50:00.162144605Z     at PullOWar.disconnect (/usr/src/app/node_modules/colyseus/lib/Room.js:161:60)
> 2018-11-04T22:50:00.162177469Z     at MatchMaker.<anonymous> (/usr/src/app/node_modules/colyseus/lib/MatchMaker.js:163:37)
> 2018-11-04T22:50:00.162255021Z     at Generator.next (<anonymous>)
> 2018-11-04T22:50:00.162285125Z     at /usr/src/app/node_modules/colyseus/lib/MatchMaker.js:7:71
> 2018-11-04T22:50:00.162313458Z     at new Promise (<anonymous>)
> 2018-11-04T22:50:00.162342989Z     at __awaiter (/usr/src/app/node_modules/colyseus/lib/MatchMaker.js:3:12)
> 2018-11-04T22:50:00.162371790Z     at MatchMaker.remoteRoomCall (/usr/src/app/node_modules/colyseus/lib/MatchMaker.js:130:16)
> 2018-11-04T22:50:00.162401009Z     at api.get (/usr/src/app/node_modules/@colyseus/monitor/lib/api.js:30:13)
> 2018-11-04T22:50:00.162429602Z     at Layer.handle [as handle_request] (/usr/src/app/node_modules/express/lib/router/layer.js:95:5)
> 2018-11-04T22:50:00.162459498Z     at next (/usr/src/app/node_modules/express/lib/router/route.js:137:13)
> 2018-11-04T22:52:08.168786243Z Error: remote room (9odFC3LIJf) timed out, requesting "disconnect with args []"
> 2018-11-04T22:52:08.168991085Z     at Timeout.setTimeout (/usr/src/app/node_modules/colyseus/lib/MatchMaker.js:155:32)
> 2018-11-04T22:52:08.169057021Z     at ontimeout (timers.js:425:11)
> 2018-11-04T22:52:08.169120198Z     at tryOnTimeout (timers.js:289:5)
> 2018-11-04T22:52:08.169179937Z     at listOnTimeout (timers.js:252:5)
> 2018-11-04T22:52:08.169241499Z     at Timer.processTimers (timers.js:212:10)
> 2018-11-04T22:54:05.280522152Z leaving

## Steps to Reproduce (for bugs)

1. add `disconnect()` trigger on an `onLeave` handler 
2. connect between two browsers
3. switch between connected browsers

## Context
It seems that the events are triggered when you actually leave the current active window.

## Your Environment

* Colyseus Version: latest 
* Node.js Version: 10
* Operating System and version: ARM Linux
* Link to your project: none

**Comment by endel** [comment]
Hi @karneaud, I couldn't reproduce here. Can you provide an example where I could see this issue happening? Thanks

**Comment by karneaud** [comment]
@endel not at this time. Had to workaround this. Hopefully sometime in the upcoming weeks.

**Comment by oyed** [comment]
@karneaud Any updates on an example?

**Comment by endel** [comment]
Closing due to inactivity. This has probably been fixed on 0.11 though. See migration guide here: https://docs.colyseus.io/migrating/0.11/
