### ISSUE TITLE
remote room (_DeGHqOh_z) timed out, requesting "locked"

### ISSUE THREAD

**Issue by Someway** [colyseus/colyseus#200]
## Steps to Reproduce (for bugs)

1. use nodejs cluster start server
2. client use bad network to connect server

## Context

remote room (_DeGHqOh_z) timed out, requesting "locked"
Error: remote room (_DeGHqOh_z) timed out, requesting "locked"
    at Timeout.setTimeout (/data/code/node-game-server/node_modules/colyseus/lib/MatchMaker.js:157:32)
    at ontimeout (timers.js:436:11)
    at tryOnTimeout (timers.js:300:5)
    at listOnTimeout (timers.js:263:5)
    at Timer.processTimers (timers.js:223:10)

## Your Environment

* Colyseus Version: 0.9.19
* Node.js Version:10.14.1
* Operating System and version: mac os
* Link to your project:

**Comment by endel** [comment]
Reported by @enriqueto as well, using a single process:

```
remote room (tanks-multiplayer/) timed out, requesting "locked". Timeout setting: 4000ms
Error: remote room (tanks-multiplayer/) timed out, requesting "locked". Timeout setting: 4000ms
    at Timeout.setTimeout (/usr/share/nginx/html/games/tanks-multiplayer/server/node_modules/colyseus/lib/MatchMaker.js:172:32)
    at ontimeout (timers.js:498:11)
    at tryOnTimeout (timers.js:323:5)
    at Timer.listOnTimeout (timers.js:290:5)
```

**Comment by endel** [comment]
The `RemoteClient` has been deprecated. The de-facto solution for scalability is still not 100% sorted out, for now, this is the way to go: https://github.com/colyseus/proxy
