### ISSUE TITLE
Matchmaker RedisPresence presence.subscribe socket issue with pm2 cluster mode

### ISSUE THREAD

**Issue by sagargirme** [colyseus/colyseus#220]
TypeError: First argument must be a valid error code number
    at Sender.close (/var/www/qm/node_modules/ws/lib/sender.js:115:13)
    at WebSocket.close (/var/www/qm/node_modules/ws/lib/websocket.js:215:18)
    at presence.subscribe (/var/www/qm/node_modules/colyseus/lib/MatchMaker.js:49:32)
    at RedisClient.subscriptions.(anonymous function) (/var/www/qm/node_modules/colyseus/lib/presence/RedisPresence.js:30:17)
    at RedisClient.emit (events.js:202:15)
    at return_pub_sub (/var/www/qm/node_modules/redis/index.js:786:18)
    at RedisClient.return_reply (/var/www/qm/node_modules/redis/index.js:833:9)
    at JavascriptRedisParser.returnReply (/var/www/qm/node_modules/redis/index.js:192:18)
    at JavascriptRedisParser.execute (/var/www/qm/node_modules/redis-parser/lib/parser.js:574:12)
    at Socket.<anonymous> (/var/www/qm/node_modules/redis/index.js:274:27)

   "colyseus.js": "0.9.15",
    "colyseus": "0.9.22",
    nodejs:11.10.0
    pm2 install redis-server command used to install redis module

 the above mention error comes once after a few hours of fine working:
the only 2 methods are subscribe when new room is init:
       this.presence.subscribe("ADD_PAYMENT_ID", this.addPaymentId);
        this.presence.subscribe("DEL_PAYMENT_ID", this.delPaymentId);

**Comment by endel** [comment]
Redis is not being used for sharing connections between rooms anymore on 0.11.x, this should not be an issue anymore
