### ISSUE TITLE
Getting started not working

### ISSUE THREAD

**Issue by alexisab** [colyseus/colyseus#230]
The code example in the [Getting started](https://docs.colyseus.io/getting-started/server/#using-javascript) doesn't work !

```
/home/alexis/Documents/projects/game/rpg/server/src/index.js:7
const gameServer = new Server({ server })
                   ^

ReferenceError: Server is not defined
    at Object.<anonymous> (/home/alexis/Documents/projects/game/rpg/server/src/index.js:7:20)
    at Module._compile (internal/modules/cjs/loader.js:689:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:700:10)
    at Module.load (internal/modules/cjs/loader.js:599:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:538:12)
    at Function.Module._load (internal/modules/cjs/loader.js:530:3)
    at Function.Module.runMain (internal/modules/cjs/loader.js:742:12)
    at startup (internal/bootstrap/node.js:279:19)
    at bootstrapNodeJSCore (internal/bootstrap/node.js:696:3)
```

You muste use `colyseus.Server` or `const { Server } = require('colyseus')`

NOTE : Same for `Create your room handler (e.g. MyRoom.js)`, `Room` is not defined

## Steps to Reproduce (for bugs)
1. Create a new project (npm init)
2. Install colyseus
3. Copy / Paste the getting started code

## Your Environment
Not related to the environment

**Comment by alexisab** [comment]
For the [client part](https://docs.colyseus.io/getting-started/javascript-client/#connecting-to-server) it doesn't work either !

`Uncaught TypeError: Cannot read property 'Client' of undefined`

We must import Colyseus like
```javascript
import * as Colyseus from 'colyseus.s'
```
... instead of 
```javascript
import Colyseus from 'colyseus.s'
```

**Comment by endel** [comment]
thanks for reporting @alexisab, I've updated the docs
