### ISSUE TITLE
Documentation is lacking basic info for v0.10

### ISSUE THREAD

**Issue by Mykybo** [colyseus/colyseus#231]
Trying to implement the new schema introduced by v0.10 I was stuck on error: `SchemaSerializer error. See: https://docs.colyseus.io/migrating/0.10/#new-default-serializer`. 

The thing is I was using the new schema so I started debugging.

It turns out I was missing a room annotation: `@serialize(SchemaSerializer)` which isn't mentioned anywhere in docs that you have to use. 

The only context this annotation is mentioned is with fossil serializer.

**Comment by endel** [comment]
hey @Mykybo, that's odd, because the `SchemaSerializer` is used by default, it shouldn't be necessary to use `@serialize(SchemaSerializer)`. How does your room handler and schema look like? Cheers

**Comment by Mykybo** [comment]
After playing around with this a bit more I am very confused... 

What I did to rule out any mistakes in my implementation of the colyseus server is copy the example server from https://github.com/colyseus/colyseus/tree/master/usage, replace the relative imports with imports from the npm package and run it.

btw, you are using the serialize decorator here:
```
@serialize(SchemaSerializer)
export class ChatRoom extends Room<State> {
```

When I run this server with the decorator, I get the following error: 
```
/src/game-server/node_modules/colyseus/lib/serializer/Serializer.js:5
        constructor.prototype._getSerializer = () => new serializer();
                                             ^

TypeError: Cannot set property '_getSerializer' of undefined
    at /mnt/c/Users/username/repository/path/node_modules/colyseus/lib/serializer/Serializer.js:5:46
    at Object.decorateConstructor (/mnt/c/Users/username/repository/path/dist/server.js:1819:3578)
    at Object.decorateClass (/mnt/c/Users/username/repository/path/dist/server.js:1819:2019)
    at _decorate (/mnt/c/Users/username/repository/path/dist/server.js:1817:308)
    at Module../src/ChatRoom.ts (/mnt/c/Users/username/repository/path/dist/server.js:1865:16)
    at __webpack_require__ (/mnt/c/Users/username/repository/path/dist/server.js:20:30)
    at Module../src/server.ts (/mnt/c/Users/username/repository/path/dist/server.js:1995:67)
    at __webpack_require__ (/mnt/c/Users/username/repository/path/dist/server.js:20:30)
    at ./node_modules/@colyseus/schema/lib/ChangeTree.js.Object.defineProperty.value (/mnt/c/Users/username/repository/path/dist/server.js:84:18)
    at Object.<anonymous> (/mnt/c/Users/username/repository/path/dist/server.js:87:10)
```
without the decorator I get my original error:
```
SchemaSerializer error. See: https://docs.colyseus.io/migrating/0.10/#new-default-serializer.
```

in my package.json:
```
  "dependencies": {
    "body-parser": "^1.18.3",
    "colyseus": "^0.10.5",
    "express": "^4.16.4"
  },
```
and on client: `"colyseus.js": "^0.10.4",`

Btw, what I said in my last post, that adding the serialize decorator fixed the error - it didn't. I just didn't notice it threw the `'_getSerializer' of undefined` error in console.

**Comment by endel** [comment]
@Mykybo 

If you're assigning anything that isn't an instance of `Schema` on `this.setState()`, you'll see the error you've mentioned:  (`SchemaSerializer error. See: https://docs.colyseus.io/migrating/0.10/#new-default-serializer.`)

You should do like this:

```typescript
import { Schema, type } from "@colyseus/schema";

class YourState extends Schema {
  // use @type() annotations to define your schema
}

///
class YourRoom extends Room {
    onInit() {
        this.setState(new YourState());
    }
}
```

**Comment by Mykybo** [comment]
I understand :). I will try to setup a simple repo which reproduces this tomorrow.

As I said, I cloned this repo and tried your implementation in the "usage" folder. It worked. When I replaced the relative imports with imports from the colyseus npm package (and changed nothing else) I got the error above.

Most likely it's something stupid, I will try tomorrow.

**Comment by endel** [comment]
@Mykybo I see, you're not supposed to use `colyseus` by cloning it. You should install it as a module (`npm install --save colyseus`), and import it from the module rather than the relative path. The [`usage/`](https://github.com/colyseus/colyseus/tree/master/usage) directory here is for internal checks only, not meant to be used.

**Comment by Mykybo** [comment]
I created: https://github.com/Mykybo/coly-test - when I connect to this server from colyseus client I get the  `colyseus.js: server error: SchemaSerializer error. See: https://docs.colyseus.io/migrating/0.10/#new-default-serializer` - can you please tell me what I did wrong in the server setup?

**Comment by endel** [comment]
I see @Mykybo, many people had issues when using Babel, see: https://discuss.colyseus.io/topic/92/colyseus-js-server-error-registeredhandler-klass-is-not-a-constructor/9 and [other posts](https://discuss.colyseus.io/search?term=babel&in=titlesposts)

You may be able to run it if you transpile `node_modules/colyseus/lib/*` files too, I haven't tested though.

I'd recommend not using webpack, and stick with plain `tsc` + `tsconfig.json`.

**Comment by Mykybo** [comment]
Webpack (with babel) is de facto the industry standard, I would rather not use colyseus than not use webpack.

Maybe, you should stop using tsc and use webpack + babel instead (or configure tsc properly), since clearly the output compiled with tsc is not compatible with some projects, instead of suggesting I use your stack...

The only reason why this incompatibility might have happened that comes to mind are the different implementations of decorators between tsc and babel, but that shouldn't be the case, since they should behave the same way anyways.

**Comment by endel** [comment]
@Mykybo yeah you're right, we need to support it. It currently works in the front-end with `colyseus.js`, but not in the back-end with `colyseus`.

**Comment by oyed** [comment]
I haven't tried 0.10.x in native/transpiled JS yet, however I do agree that non-TS should be the standard here - as mentioned, it's the defacto industry standard, and TS is additional on-top of this should be an extra.

**Comment by endel** [comment]
I've been playing around with this today, and I've managed to get rid of the `SchemaSerializer error` using this configuration: https://github.com/endel/coly-test/commit/c45d9d1ce6ce16b7a5db7b16f4f88ac6c599ce8e

The problem is deeper than it seems, though. Babel currently cannot play nicely with TypeScript's ("legacy") decorators, here are some relevant issues on their issue tracker:
- https://github.com/babel/babel/issues/9779
- https://github.com/babel/babel/issues/9773

I believe the root of this issue is because of the `initializerDefineProperty_default` calls generated by Babel, here:

```javascript
let TestRoom_State = (_dec = Object(schema_["type"])("string"), _dec2 = Object(schema_["type"])("number"), (_class = (_temp = class State extends schema_["Schema"] {
  constructor() {
    super(...arguments);

    initializerDefineProperty_default()(this, "someAtr", _descriptor, this);
//...
```

Unfortunately I'm not sure how high is for the Babel team to fix this.

**Comment by Mykybo** [comment]
@endel The changes to the config in https://github.com/endel/coly-test/commit/c45d9d1ce6ce16b7a5db7b16f4f88ac6c599ce8e do allow the project to be compiled, room to be created and clients to join, however, state updates are not sent to client. 

When I compile the same project with `tsc`, the updates start working.

**Comment by endel** [comment]
A pull-request landed recently on Babel to improve some legacy decorators stuff https://github.com/babel/babel/pull/10616

I've updated the test scenario for the latest versions (https://github.com/endel/coly-test) and the same error (not synching state data) can be observed

**Comment by endel** [comment]
I believe this is not an issue anymore, feel free to reopen if still a problem
