### ISSUE TITLE
Error ？？？ 

### ISSUE THREAD

**Issue by crh5354** [colyseus/colyseus#262]
fengdeMac-mini-2:my-colyseus-server feng$ npm start

> my-app@1.0.0 start /Users/feng/my-colyseus-server
> ts-node index.ts

Listening on ws://localhost:2567
Error connecting to database:  { MongoNetworkError: failed to connect to server [127.0.0.1:27017] on first connect [MongoNetworkError: connect ECONNREFUSED 127.0.0.1:27017]
    at Pool.<anonymous> (/Users/feng/my-colyseus-server/node_modules/mongodb-core/lib/topologies/server.js:431:11)
    at Pool.emit (events.js:198:13)
    at Pool.EventEmitter.emit (domain.js:448:20)
    at connect (/Users/feng/my-colyseus-server/node_modules/mongodb-core/lib/connection/pool.js:557:14)
    at makeConnection (/Users/feng/my-colyseus-server/node_modules/mongodb-core/lib/connection/connect.js:39:11)
    at callback (/Users/feng/my-colyseus-server/node_modules/mongodb-core/lib/connection/connect.js:261:5)
    at Socket.err (/Users/feng/my-colyseus-server/node_modules/mongodb-core/lib/connection/connect.js:286:7)
    at Object.onceWrapper (events.js:286:20)
    at Socket.emit (events.js:198:13)
    at Socket.EventEmitter.emit (domain.js:448:20)
    at emitErrorNT (internal/streams/destroy.js:91:8)
    at emitErrorAndCloseNT (internal/streams/destroy.js:59:3)
    at process._tickCallback (internal/process/next_tick.js:63:19)
  name: 'MongoNetworkError',
  errorLabels: [ 'TransientTransactionError' ],
  [Symbol(mongoErrorContextSymbol)]: {} }

why? run at the macOS

**Comment by endel** [comment]
Hi @crh5354,

`@colyseus/social` requires MongoDB installed. If you don't want to use authentication you can remove these lines:
- https://github.com/colyseus/create-colyseus-app/blob/123af18a9c6c32e635933544f8c67de08af32a17/index.ts#L6
- https://github.com/colyseus/create-colyseus-app/blob/123af18a9c6c32e635933544f8c67de08af32a17/index.ts#L26

**Comment by crh5354** [comment]
@endel Thx!
