### ISSUE TITLE
when throw error, nodejs.TypeError: Cannot read property 'port' of null

### ISSUE THREAD

**Issue by dengzhaofun** [colyseus/colyseus#296]
colyseus:errors TypeError: Cannot read property 'discardAllChanges' of undefined
  colyseus:errors     at GameRoomState.Schema.discardAllChanges (/Users/dengzhao/Qsync/project/juju/juju-server/node_modules/_@colyseus_schema@0.5.23@@colyseus/schema/src/Schema.ts:746:42)
  colyseus:errors     at SchemaSerializer.applyPatches (/Users/dengzhao/Qsync/project/juju/juju-server/node_modules/_colyseus@0.12.0@colyseus/lib/serializer/SchemaSerializer.js:50:28)
  colyseus:errors     at TNRoom.broadcastPatch (/Users/dengzhao/Qsync/project/juju/juju-server/node_modules/_colyseus@0.12.0@colyseus/lib/Room.js:312:33)
  colyseus:errors     at Timeout._onTimeout (/Users/dengzhao/Qsync/project/juju/juju-server/node_modules/_colyseus@0.12.0@colyseus/lib/Room.js:100:22)
  colyseus:errors     at listOnTimeout (internal/timers.js:531:17)
  colyseus:errors     at processTimers (internal/timers.js:475:7) +67ms
2020-01-28 23:05:38,304 ERROR 63592 nodejs.TypeError: Cannot read property 'port' of null
    at Server.<anonymous> (/Users/dengzhao/Qsync/project/juju/juju-server/node_modules/_colyseus@0.12.0@colyseus/lib/Server.js:94:47)
    at Generator.next (<anonymous>)
    at /Users/dengzhao/Qsync/project/juju/juju-server/node_modules/_colyseus@0.12.0@colyseus/lib/Server.js:8:71
    at new Promise (<anonymous>)
    at __awaiter (/Users/dengzhao/Qsync/project/juju/juju-server/node_modules/_colyseus@0.12.0@colyseus/lib/Server.js:4:12)
    at Server.gracefullyShutdown (/Users/dengzhao/Qsync/project/juju/juju-server/node_modules/_colyseus@0.12.0@colyseus/lib/Server.js:92:16)
    at /Users/dengzhao/Qsync/project/juju/juju-server/node_modules/_colyseus@0.12.0@colyseus/lib/Server.js:49:60
    at process.<anonymous> (/Users/dengzhao/Qsync/project/juju/juju-server/node_modules/_colyseus@0.12.0@colyseus/lib/Utils.js:19:9)
    at process.emit (events.js:228:7)
    at process.emit (/Users/dengzhao/Qsync/project/juju/juju-server/node_modules/_source-map-support@0.5.16@source-map-support/source-map-support.js:485:21)
    at process._fatalException (internal/process/execution.js:150:25)

**Comment by endel** [comment]
Hi @dengzhaofun, looks like this is a bug on @colyseus/schema during the `discardAllChanges ()` method, while using filters. I've just published `@colyseus/schema@0.5.24`.

Can you try removing the `node_modules` + `package-lock.json`, and then installing the modules again, to see if it works?

```
rm -R node_modules package-lock.json
npm install
```

**Comment by dengzhaofun** [comment]
discardAllChanges The problem that caused the exception to be thrown has been resolved
but As long as the engine throws any exception, always show error Cannot read property 'port' of null
_colyseus@0.12.0@colyseus/lib/Server.js:94:47 port is null.

**Comment by endel** [comment]
I see, thanks. What's the Node.js version and operating system you're using @dengzhaofun? 👀 

I've haven't seen this error yet, but it's harmless - occurs during shutting down of the application. Just tagged this as a "bug" until it gets fixed!

**Comment by dengzhaofun** [comment]
Node.js version: v12.14.1
system: Mac
