### ISSUE TITLE
How do class members support dynamic typing through generics?

### ISSUE THREAD

**Issue by dengzhaofun** [colyseus/colyseus#301]
```
export class GameRoomState<RoomConfigType extends RoomConfig = any> extends Schema {

  @type([Schema])
  roomConfig: RoomConfigType
}
```
This will produce errors, so how can I achieve the goal

Error: TCL: GameRoom -> onCreate -> roomId 391696
TypeError: Invalid value used in weak set
    at WeakSet.add (<anonymous>)
    at SchemaSerializer.hasFilter (/Users/dengzhao/Qsync/project/juju/juju-server/node_modules/_colyseus@0.12.0@colyseus/lib/serializer/SchemaSerializer.js:65:22)
    at SchemaSerializer.hasFilter (/Users/dengzhao/Qsync/project/juju/juju-server/node_modules/_colyseus@0.12.0@colyseus/lib/serializer/SchemaSerializer.js:88:38)
    at SchemaSerializer.reset (/Users/dengzhao/Qsync/project/juju/juju-server/node_modules/_colyseus@0.12.0@colyseus/lib/serializer/SchemaSerializer.js:14:40)
    at TNRoom.setState (/Users/dengzhao/Qsync/project/juju/juju-server/node_modules/_colyseus@0.12.0@colyseus/lib/Room.js:113:26)
    at TNRoom.onCreate (/Users/dengzhao/Qsync/project/juju/juju-server/app/room/gameRoom.ts:35:10)
    at processTicksAndRejections (internal/process/task_queues.js:94:5)

**Comment by endel** [comment]
Hi @dengzhaofun, `@colyseus/schema` does support inheritance, so if you have a base `RoomConfig` that extends from `Schema`, you can define your type as an array of `RoomConfig`. 

**Example:**

```typescript
abstract class RoomConfig extends Schema {
  @type("string") defaultValue: string;
}

class ConcreteConfig extends Schema {
  @type("string") specificValue: string;
}

export class GameRoomState<RoomConfigType extends RoomConfig = any> extends Schema {
  @type(RoomConfig) 
  roomConfig: RoomConfigType
}
```

I've changed your `GameRoomState` to use a direct reference (`@type(RoomConfig)`) instead of an array of configs (`@type([RoomConfig])`), but that depends on your needs.
