### ISSUE TITLE
state Array <classType> index is null throw exception

### ISSUE THREAD

**Issue by dengzhaofun** [colyseus/colyseus#302]
Null is set on the state array property index, causing an exception to crash, splice works, but I do need to null the index to represent that this position is empty.

```
  exit(client: Client, message: any) {
    if (this.fsm.state !== 'ready') {
      this.send(client, { event: message.event, code: API_Code.ROOM_STATE_CAN_NOT_LEAVE })
      return
    }
    const index = _.findIndex(this.state.players, { sessionId: client.sessionId })
    if (index === -1) {
      this.send(client, { event: message.event, code: API_Code.NOT_FOUND_USER })
      return
    }
    this.state.players[index] = null
    client.close()
  }
```

throw error: TypeError: Cannot read property 'constructor' of null
    at assertInstanceType (/Users/dengzhao/Qsync/project/juju/juju-server/node_modules/_@colyseus_schema@0.5.24@@colyseus/schema/src/Schema.ts:60:91)
    at _loop_2 (/Users/dengzhao/Qsync/project/juju/juju-server/node_modules/_@colyseus_schema@0.5.24@@colyseus/schema/src/Schema.ts:514:25)
    at GameRoomState.Schema.encode (/Users/dengzhao/Qsync/project/juju/juju-server/node_modules/_@colyseus_schema@0.5.24@@colyseus/schema/lib/Schema.js:574:13)
    at SchemaSerializer.applyPatches (/Users/dengzhao/Qsync/project/juju/juju-server/node_modules/_colyseus@0.12.0@colyseus/lib/serializer/SchemaSerializer.js:31:44)
    at TNRoom.broadcastPatch (/Users/dengzhao/Qsync/project/juju/juju-server/node_modules/_colyseus@0.12.0@colyseus/lib/Room.js:312:33)
    at Timeout._onTimeout (/Users/dengzhao/Qsync/project/juju/juju-server/node_modules/_colyseus@0.12.0@colyseus/lib/Room.js:100:22)
    at listOnTimeout (internal/timers.js:531:17)
    at processTimers (internal/timers.js:475:7)

**Comment by endel** [comment]
Hi @dengzhaofun, the Schema types are strongly typed - if you have an array of numbers I'd suggest using `0` or `-1` to represent the empty positions. Feel free to reopen if you have any questions

**Comment by dengzhaofun** [comment]
Ok i will use a separate array to maintain seat availability. Thanks @endel
