### ISSUE TITLE
When the function gracefullyShutdown is called it must throw an exception.

### ISSUE THREAD

**Issue by dengzhaofun** [colyseus/colyseus#306]
When the function gracefullyShutdown is called it must throw an exception,I hope the official can solve it as soon as possible, and the product will be ready for launch in a week.

```
TypeError: Cannot read property 'port' of null
    at Server.<anonymous> (/Users/dengzhao/Qsync/project/juju/juju-server/node_modules/_colyseus@0.12.0@colyseus/lib/Server.js:94:47)
    at Generator.next (<anonymous>)
    at /Users/dengzhao/Qsync/project/juju/juju-server/node_modules/_colyseus@0.12.0@colyseus/lib/Server.js:8:71
    at new Promise (<anonymous>)
    at __awaiter (/Users/dengzhao/Qsync/project/juju/juju-server/node_modules/_colyseus@0.12.0@colyseus/lib/Server.js:4:12)
    at Server.gracefullyShutdown (/Users/dengzhao/Qsync/project/juju/juju-server/node_modules/_colyseus@0.12.0@colyseus/lib/Server.js:92:16)
    at AppBootHook.beforeClose (/Users/dengzhao/Qsync/project/juju/juju-server/app.ts:129:25)
    at Object.callFn (/Users/dengzhao/Qsync/project/juju/juju-server/node_modules/_egg-core@4.17.4@egg-core/lib/utils/index.js:44:42)
    at Lifecycle.close (/Users/dengzhao/Qsync/project/juju/juju-server/node_modules/_egg-core@4.17.4@egg-core/lib/lifecycle.js:123:19)
    at Application.close (/Users/dengzhao/Qsync/project/juju/juju-server/node_modules/_egg-core@4.17.4@egg-core/lib/egg.js:288:42)
    at beforeExit (/Users/dengzhao/Qsync/project/juju/juju-server/node_modules/_egg-cluster@1.26.0@egg-cluster/lib/app_worker.js:116:25)
    at /Users/dengzhao/Qsync/project/juju/juju-server/node_modules/_graceful-process@1.2.0@graceful-process/exit.js:16:16
    at processTicksAndRejections (internal/process/task_queues.js:94:5)

```

**Comment by dengzhaofun** [comment]
Processes run in a node cluster @endel

**Comment by endel** [comment]
Cluster mode is not currently supported, we can continue the discussion on your other https://github.com/colyseus/colyseus/issues/307
