### ISSUE TITLE
Jump between rooms is not working

### ISSUE THREAD

**Issue by MateusMendesSantana** [colyseus/colyseus#332]
Hi, after upgrading to version 0.13.0 the jump stopped working, "jump between rooms" means leaving a room, as in the example below, and then entering another.
![image](https://user-images.githubusercontent.com/35671729/80866903-b1291080-8c67-11ea-82ad-e8449cbf50e1.png)

When I just enter or leave a room everything happens correctly, without errors, but when trying to leave and enter immediately, the following error occurs at the entrance:
```
PlaceRoom 5eab46239bcb7500076ec446 created!
client joined! X93xzj2rd
disconnected! X93xzj2rd
5eab46239bcb7500076ec446 closed and saved

Error: seat reservation expired.
    at WebSocketServer.<anonymous> (D:\projects\smadol\smadol-server\node_modules\colyseus\lib\transport\WebSocket\WebSocketTransport.js:100:27)
    at Generator.next (<anonymous>)
    at D:\projects\smadol\smadol-server\node_modules\colyseus\lib\transport\WebSocket\WebSocketTransport.js:8:71
    at new Promise (<anonymous>)
    at D:\projects\smadol\smadol-server\node_modules\colyseus\lib\transport\WebSocket\WebSocketTransport.js:4:12
    at WebSocketServer.onConnection (D:\projects\smadol\smadol-server\node_modules\colyseus\lib\transport\WebSocket\WebSocketTransport.js:84:16)
    at WebSocketServer.emit (events.js:311:20)
    at D:\projects\smadol\smadol-server\node_modules\ws\lib\websocket-server.js:90:18
    at WebSocketServer.completeUpgrade (D:\projects\smadol\smadol-server\node_modules\ws\lib\websocket-server.js:329:5)
    at WebSocketServer.handleUpgrade (D:\projects\smadol\smadol-server\node_modules\ws\lib\websocket-server.js:245:10)
    at Server.upgrade (D:\projects\smadol\smadol-server\node_modules\ws\lib\websocket-server.js:89:16)
    at Server.emit (events.js:311:20)
    at onParserExecuteCommon (_http_server.js:642:14)
    at onParserExecute (_http_server.js:583:3)
```

Workaround on client:
![image](https://user-images.githubusercontent.com/35671729/80867036-63f96e80-8c68-11ea-9805-805c00bcd9c8.png)
waiting 300ms after leaving the room to enter again, this error stops occurring.

**Comment by endel** [comment]
That's interesting @MateusMendesSantana, thanks for reporting. Theoretically, nothing has changed regarding this on version 0.13.0. 

Can you send me both your client and server implementation for me to reproduce? I'll find some time to check this during the week. You can find my email address on my GitHub profile. Cheers!

**Comment by MateusMendesSantana** [comment]
I tried to create a small project reproducing the error, but I couldn't do it. However I discovered a problem in my own project, each room represents a document in the database, so, when creating it, I set the roomId to the document's id value.
```
async onCreate(options: any) {
    const place = await PlaceRepository.findById(options.id).exec();

    if (place) {
      this.roomId = place.id.toString();
      this.setState(new Place(place.toObject()));

      ........
    } else {
      this.disconnect();
    }
  }
```
I was entering the room using JoinOrCreate by passing the room Id in options, I think this worked before because of the filter in the room in requestJoin that has now been removed.

I did this method and got the behavior described previously ;D
```
public async Task<Room<T>> JoinByIdOrCreate<T> (string roomName, string roomId) where T : Schema {
    var options = new Dictionary<string, object> () {
      {"id", roomId},
      {"create", true}
    };

    try {
      return await client.JoinById<T> (roomId);
    } catch (Exception error) {
      var matchMakeException = error as MatchMakeException;

      if (matchMakeException != null && matchMakeException.Code == 4212) {
        return await client.Create<T> (roomName, options);
      } else {
        throw error;
      }
    }
  }
```
After this adjustment I removed the temporary solution:
`await WaitSeconds(200);`
Almost everything worked correctly. When I jump to a different room now everything works correctly, but if I jump to the same room the error happens. So I conclude that this error (Error: seat reservation expired.) Happens when leaving and immediately trying to enter the same room.

**Comment by endel** [comment]
Hi @MateusMendesSantana, I'm going to close this as it seems to have been a bug on your end (?), feel free to re-open if you still have this issue! Cheers!
