### ISSUE TITLE
UnhandledPromiseRejectionWarning: TypeError: Cannot read property 'indexOf' of null

### ISSUE THREAD

**Issue by HishamMubarak** [colyseus/colyseus#390]
## Steps to Reproduce (for bugs)
1. Call this.dispose() inside a this.clock.setTimeout

## Context
I am trying to automatically dispose a room after a couple of minutes and forcefully disconnect user using this.dispose().
Here is my code

```
this.automaticDisposeTimeout = this.clock.setTimeout(() => {
     // "Automatically dispose room after 10 seconds"
     this.disconnect()
}, 1000)
```

Anytime this timeout is reached, I get the following error
```
(node:13229) UnhandledPromiseRejectionWarning: TypeError: Cannot read property 'indexOf' of null
    at RoomCache.remove (/Users/hishammubarak/psc/server/node_modules/colyseus/lib/matchmaker/drivers/LocalDriver/RoomData.js:53:39)
    at BattleRoom.<anonymous> (/Users/hishammubarak/psc/server/node_modules/colyseus/lib/Room.js:229:32)
    at Generator.next (<anonymous>)
    at /Users/hishammubarak/psc/server/node_modules/colyseus/lib/Room.js:27:71
    at new Promise (<anonymous>)
    at __awaiter (/Users/hishammubarak/psc/server/node_modules/colyseus/lib/Room.js:23:12)
    at BattleRoom.disconnect (/Users/hishammubarak/psc/server/node_modules/colyseus/lib/Room.js:227:16)
    at BattleRoom.onLeave (/Users/hishammubarak/psc/server/rooms/BattleRoom.js:343:22)
    at BattleRoom.<anonymous> (/Users/hishammubarak/psc/server/node_modules/colyseus/lib/Room.js:506:32)
    at Generator.next (<anonymous>)
    at /Users/hishammubarak/psc/server/node_modules/colyseus/lib/Room.js:27:71
    at new Promise (<anonymous>)
    at __awaiter (/Users/hishammubarak/psc/server/node_modules/colyseus/lib/Room.js:23:12)
    at BattleRoom._onLeave (/Users/hishammubarak/psc/server/node_modules/colyseus/lib/Room.js:500:16)
    at BattleRoom._forciblyCloseClient (/Users/hishammubarak/psc/server/node_modules/colyseus/lib/Room.js:497:14)
    at BattleRoom.<anonymous> (/Users/hishammubarak/psc/server/node_modules/colyseus/lib/Room.js:239:26)
```

The error seems to be generated at the following file
node_modules/colyseus/lib/matchmaker/drivers/LocalDriver/RoomData.js
At Line 52 in a method called remove()

```
remove() {
        const roomIndex = this.$rooms.indexOf(this);
        if (roomIndex === -1) {
            return;
        }
        Utils_1.spliceOne(this.$rooms, roomIndex);
        this.$rooms = null;
    }
```

##  Environment
* Colyseus Version: 14.4
* Node.js Version: 14.8.0
* Operating System and version: MacOS BigSur

**Comment by endel** [comment]
Thanks for reporting @HishamMubarak, I did experience rarely during development. I've just pushed a workaround for this (version 0.14.6). Please let me know if you have any feedback!

**Comment by TeeTeeHaa** [comment]
I had the same error with version 1.14.4. It happened only while at least one client was connected.
For me the error is gone after upgrading to version 1.14.6.
