### ISSUE TITLE
[Class] is not a constructor

### ISSUE THREAD

**Issue by akaadream** [colyseus/colyseus#408]
Hi, i'm working on a project where when i'm trying to connect a client to the Colyseus server, i got this error on most of project classes :
```
Listening on ws://localhost:2567
TypeError: Museum_1.Museum is not a constructor
    at MuseumRoom.onCreate (D:\Programmation\Web\hyperfiction-albertville-nodejs\src\rooms\MuseumRoom.ts:73:23)
    at D:\Programmation\Web\hyperfiction-albertville-nodejs\node_modules\colyseus\src\MatchMaker.ts:276:18
    at Generator.next (<anonymous>)
    at D:\Programmation\Web\hyperfiction-albertville-nodejs\node_modules\colyseus\lib\MatchMaker.js:8:71
    at new Promise (<anonymous>)
    at __awaiter (D:\Programmation\Web\hyperfiction-albertville-nodejs\node_modules\colyseus\lib\MatchMaker.js:4:12)
    at handleCreateRoom (D:\Programmation\Web\hyperfiction-albertville-nodejs\node_modules\colyseus\lib\MatchMaker.js:210:12)
    at D:\Programmation\Web\hyperfiction-albertville-nodejs\node_modules\colyseus\src\MatchMaker.ts:228:18
    at Generator.next (<anonymous>)
    at fulfilled (D:\Programmation\Web\hyperfiction-albertville-nodejs\node_modules\colyseus\lib\MatchMaker.js:5:58)
```
In this case, Museum is a Schema. But i got the same issue with simple classes. 
By the way, the project is pushed on my job's server and we don't have this issue. I got this issue from the beginning of the teleworking when i tried to install the project on my personnal computer.

Thank you in advance !

**Comment by endel** [comment]
Hi @akaadream, sounds like some problem importing your classes? If you `console.log()` them right after importing what do you see? Also, make sure you don't have the compiled `.js` files at the same level as the `.ts` files to avoid importing the compiled ones by mistake.

**Comment by akaadream** [comment]
I got this, it's looking good
![image](https://user-images.githubusercontent.com/18325858/116562770-be70ed80-a903-11eb-9c8b-1a53a800e678.png)
