### ISSUE TITLE
Unable to start the starter code on windows

### ISSUE THREAD

**Issue by nipundavid** [colyseus/colyseus#457]
I have downloaded the sample example server from git, and have installed all the dependecies.

At npm start, I am getting error of .env 

```
[INFO] 22:10:16 ts-node-dev ver. 1.1.8 (using ts-node ver. 9.1.1, typescript ver. 3.9.10)
D:\Workspace\FreakX\Multiplayer\colyseusBareBone\my-colyseus-server\node_modules\@colyseus\arena\build\index.js:37
        path__default['default'].resolve(path__default['default'].dirname(require?.main?.filename || process.cwd()), "..", envFilename),
                                                                                  ^

SyntaxError: Unexpected token .
    at Module._compile (internal/modules/cjs/loader.js:723:23)
    at Module._compile (D:\Workspace\FreakX\Multiplayer\colyseusBareBone\my-colyseus-server\node_modules\source-map-support\source-map-support.js:568:25)
    at Module._extensions..js (internal/modules/cjs/loader.js:789:10)
    at require.extensions..jsx.require.extensions..js (C:\Users\NIPUND~1\AppData\Local\Temp\ts-node-dev-hook-13348380053884457.js:114:20)
    at Object.nodeDevHook [as .js] (D:\Workspace\FreakX\Multiplayer\colyseusBareBone\my-colyseus-server\node_modules\ts-node-dev\lib\hook.js:63:13)
    at Module.load (internal/modules/cjs/loader.js:653:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:593:12)
    at Function.Module._load (internal/modules/cjs/loader.js:585:3)
    at Module.require (internal/modules/cjs/loader.js:692:17)
    at require (internal/modules/cjs/helpers.js:25:18)
[ERROR] 22:10:17 SyntaxError: Unexpected token .
```

## Steps to Reproduce (for bugs)

1.  git clone https://github.com/colyseus/colyseus.git
2.  cd my-colyseus-server
3. npm install
4. npm start

## Context
![image](https://user-images.githubusercontent.com/2108309/136246696-eea8bb02-f24c-470d-9375-8bdda89bd86a.png)

## Your Environment

* Colyseus Version: https://github.com/colyseus/colyseus
* Node.js Version: v10.16.2
* Operating System and version: Windows 10

**Comment by endel** [comment]
Hi @nipundavid, please upgrade to Node.js v16 or higher and it should work fine!

Node.js v14 is going to reach the end of maintenance mode next year.
