### ISSUE TITLE
Error after Migration from 0.13 to 0.14 

### ISSUE THREAD

**Issue by saeidalidadi** [colyseus/colyseus#470]
https://github.com/colyseus/colyseus/blob/0dc966f9f3e161c63a7929486beaa8a6e11a7e2d/packages/core/src/Protocol.ts#L76

This error had occurred after migration from `0.13` to `0.14.18`:

```
TypeError: bytes is not iterable
    at Object.14 (/home/jjn/Projects/test-game/node_modules/@colyseus/core/build/Protocol.js:73:49)
    at Server.sendFullState (/home/jjn/Projects/test-game/node_modules/@colyseus/core/build/Room.js:359:81)
    at Server._onMessage (/home/jjn/Projects/test-game/node_modules/@colyseus/core/build/Room.js:466:22)
    at WebSocket.emit (events.js:400:28)
    at Receiver.receiverOnMessage (/home/jjn/Projects/test-game/node_modules/ws/lib/websocket.js:983:20)
    at Receiver.emit (events.js:400:28)
    at Receiver.dataMessage (/home/jjn/Projects/test-game/node_modules/ws/lib/receiver.js:502:14)
    at Receiver.getData (/home/jjn/Projects/test-game/node_modules/ws/lib/receiver.js:435:17)
    at Receiver.startLoop (/home/jjn/Projects/test-game/node_modules/ws/lib/receiver.js:143:22)
    at Receiver._write (/home/jjn/Projects/test-game/node_modules/ws/lib/receiver.js:78:10)
    at writeOrBuffer (internal/streams/writable.js:358:12)
    at Receiver.Writable.write (internal/streams/writable.js:303:10)
    at Socket.socketOnData (/home/jjn/Projects/test-game/node_modules/ws/lib/websocket.js:1077:35)
    at Socket.emit (events.js:400:28)
    at addChunk (internal/streams/readable.js:290:12)
    at readableAddChunk (internal/streams/readable.js:265:9)

```

**Comment by saeidalidadi** [comment]
I should remove this issue due to the fix after adding `schemas` to `server state`

**Comment by baochungit** [comment]
What causes this error? In my case, it happens when I use setState.
Here is my code:

```
import { Schema, type } from "@colyseus/schema";
class LobbyState extends Schema {
  @type("string")
  custom: string = null;
}

export class LobbyRoom extends Room {
  async onCreate(options: any) {
    this.setState(new LobbyState());
  }
  ...
}
```

**Comment by endel** [comment]
@baochungit please check if you're also using the latest version of the client. Both server and client must use the same version (0.14.x)

**Comment by baochungit** [comment]
> @baochungit please check if you're also using the latest version of the client. Both server and client must use the same version (0.14.x)

Maybe that is. I've just reinstalled node_modules then the error was gone.
