### ISSUE TITLE
onAuth in colyseus 11 getting errors when return false

### ISSUE THREAD

**Issue by hdev72** [colyseus/colyseus#490]
hello dear friends
im using colyseus 11 and cant import ServerError so without ServerError i try onAuth
im getting this error when trying onAuth

Error: onAuth failed.
    at GameRoom.<anonymous> (D:\Android_Studio\Projectss\PlayMafia\Server matchmaking colyseus\serverRanked\node_modules\colyseus\lib\Room.js:266:31)
    at Generator.next (<anonymous>)
    at fulfilled (D:\Android_Studio\Projectss\PlayMafia\Server matchmaking colyseus\serverRanked\node_modules\colyseus\lib\Room.js:5:58)
    at processTicksAndRejections (internal/process/task_queues.js:95:5)
Error: onAuth failed.
    at GameRoom.<anonymous> (D:\Android_Studio\Projectss\PlayMafia\Server matchmaking colyseus\serverRanked\node_modules\colyseus\lib\Room.js:266:31)
    at Generator.next (<anonymous>)
    at fulfilled (D:\Android_Studio\Projectss\PlayMafia\Server matchmaking colyseus\serverRanked\node_modules\colyseus\lib\Room.js:5:58)
    at processTicksAndRejections (internal/process/task_queues.js:95:5)
dont has key error

with e simple onAuth code only getting error when returns false :

    async onAuth (client: Client, options?: any, request?: any) {
            return false
      }

**Comment by hdev72** [comment]
please help me guys

**Comment by oyed** [comment]
Hey there - if `onAuth` returns `false` or throws an `Error`, then entry to the room is denied. Return true or any other value to allow entry.
