### ISSUE TITLE
how create game handler methods in class extends from Room? [ resolved ]

### ISSUE THREAD

**Issue by hdev72** [colyseus/colyseus#491]
hello dear friends
im getting error when calling methods in class extends from room
( i think methods with non input like triggerPhaseEnd working but method startNextPhase not work )

here is my example :

onJoin?(client: Client, options?: any, auth?: any): void | Promise<any> {
  logger('Game Room onJoin');

   setTimeout(this.triggerPhaseEnd, 1000);
}

triggerPhaseEnd(): void{
    this.startNextPhase(1000);  // here im getting following error:  TypeError: this.startNextPhase is not a function
}

startNextPhase(currentPhase: number = 1): void {
  logger('startNextPhase', 1, this.enableLogs);
}

console error:
TypeError: this.startNextPhase is not a function
    at Timeout.triggerPhaseEnd [as _onTimeout] (D:\Android_Studio\Projectss\PlayMafia\Server matchmaking colyseus\serverRanked\src\GameRoom.ts:320:14)
    at listOnTimeout (internal/timers.js:557:17)
    at processTimers (internal/timers.js:500:7)

**Comment by hdev72** [comment]
i found a good example it
https://github.com/halftheopposite/TOSIOS/blob/master/packages/server/src
( methods should on game state class)
