### ISSUE TITLE
migrating to 14 Package subpath './lib/encoding/encode' is not defined by "exports" in ..... node_modules\@colyseus\schema\package.json

### ISSUE THREAD

**Issue by hdev72** [colyseus/colyseus#501]
hello dear friends
when i migrating from 13 to 14 in server side(npm install colyseus@^0.14.0 --save)  im getting this error:

Package subpath './lib/encoding/encode' is not defined by "exports" in ..... node_modules\@colyseus\schema\package.json
at throwExportsNotFound (internal/modules/esm/resolve.js:285:9)
    at packageExportsResolve (internal/modules/esm/resolve.js:508:3)
    at resolveExports (internal/modules/cjs/loader.js:450:36)
    at Function.Module._findPath (internal/modules/cjs/loader.js:490:31)
    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:888:27)
    at Function.Module._load (internal/modules/cjs/loader.js:746:27)
    at Module.require (internal/modules/cjs/loader.js:974:19)
    at require (internal/modules/cjs/helpers.js:92:18)
    at Object.<anonymous> (D:\Android_Studio\Projectss\...\Server JavaScript\serverRanked\node_modules\colyseus\src\Protocol.ts:4:1)
    at Module._compile (internal/modules/cjs/loader.js:1085:14)

pls help me 
thank you so much

**Comment by endel** [comment]
Hi @hdev72, are you still getting this error? Did you upgrade `@colyseus/schema` as well?

**Comment by hdev72** [comment]
Hello dear friend, no and i cant remember how i solved this error.
