### ISSUE TITLE
TypeError: Cannot read property 'constructor' of undefined

### ISSUE THREAD

**Issue by hdev72** [colyseus/colyseus#502]
hello every one
im getting this error and cant fix it
do you know what is this i don have any constractor in my codes and changed all to .assign (migrating 14)

Error [ERR_PACKAGE_PATH_NOT_EXPORTED]: Package subpath './lib/encoding/encode' is not defined by "exports" in D:\Android_Studio\Projectss\PlayMafia\Server JavaScript\serverRanked\node_modules\colyseus\node_modules\@colyseus\schema\package.json
    at throwExportsNotFound (internal/modules/esm/resolve.js:285:9)
    at packageExportsResolve (internal/modules/esm/resolve.js:508:3)
    at resolveExports (internal/modules/cjs/loader.js:450:36)
    at Function.Module._findPath (internal/modules/cjs/loader.js:490:31)
    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:888:27)
    at Function.Module._load (internal/modules/cjs/loader.js:746:27)
    at Module.require (internal/modules/cjs/loader.js:974:19)
    at require (internal/modules/cjs/helpers.js:92:18)
    at Object.<anonymous> (D:\...\serverRanked\node_modules\colyseus\src\Protocol.ts:4:1)
    at Module._compile (internal/modules/cjs/loader.js:1085:14)

after solving above error with npm update getting new error:

TypeError: Cannot read property 'constructor' of undefined
    at assertInstanceType (D:\ ... \serverRanked\node_modules\@colyseus\schema\src\Schema.ts:85:91)
    at GameState.Schema.encode (D:\ ... \serverRanked\node_modules\@colyseus\schema\src\Schema.ts:603:21)
    at SchemaSerializer.applyPatches (D:\ ... \serverRanked\node_modules\@colyseus\core\src\serializer\SchemaSerializer.ts:47:34)
    at GameRoom.broadcastPatch (D:\ ... \serverRanked\node_modules\@colyseus\core\src\Room.ts:280:41)
    at Timeout._onTimeout (D:\ ... \serverRanked\node_modules\@colyseus\core\src\Room.ts:157:52)
    at listOnTimeout (internal/timers.js:557:17)
    at processTimers (internal/timers.js:500:7)

**Comment by hdev72** [comment]
resolved:
if MapSchema key is not string you will see this error : Cannot read property 'constructor' of undefined
It was very difficult for me to find this topic after one day: D
