### ISSUE TITLE
Crash in schema

### ISSUE THREAD

**Issue by dan-merlea** [colyseus/colyseus#561]
0|Game     | TypeError: Cannot read properties of undefined (reading 'constructor')
0|Game     |     at assertInstanceType (@colyseus/schema/src/Schema.ts:85:91)
0|Game     |     at GameState.Schema.encode (@colyseus/schema/src/Schema.ts:604:21)
0|Game     |     at GameState.Schema.encodeAll (@colyseus/schema/src/Schema.ts:656:21)
0|Game     |     at SchemaSerializer.getFullState (@colyseus/core/src/serializer/SchemaSerializer.ts:25:41)
0|Game     |     at GameRoom.sendFullState (@colyseus/core/src/Room.ts:476:77)
0|Game     |     at GameRoom._onMessage (@colyseus/core/src/Room.ts:614:14)
0|Game     |     at uWebSocketWrapper.emit (node:events:527:28)
0|Game     |     at message (@colyseus/uwebsockets-transport/src/uWebSocketsTransport.ts:100:46)

## Context
I keep seeing these in the console and it's crashing the server a few times a day. 

## Your Environment

* Colyseus Version: 1.0.45
*

**Comment by endel** [comment]
Hi @dan-merlea,

This error means you have an `undefined` structure within your schema objects. The error is thrown during encoding rather than during assignment. I'd recommend checking in your latest additions where a possible `undefined` could have emerged.

**Comment by endel** [comment]
Another similar error that has been reported before is: `"Cannot read properties of undefined (reading '$changes')"`. I'm very curious to find the reason these happen so the library can display a better error message pointing to a solution.

**Comment by dan-merlea** [comment]
Hello, 
I do have an optional object that I put as undefined sometimes. Would that cause the issue? Or what do you mean by undefined structure?

**Comment by endel** [comment]
An optional property should be fine to be set as `undefined`! If you can share your structures and the types of operations you use could help to find out the reason. (If you can't share it publicly please send it to my email at endel@colyseus.io)

**Comment by dan-merlea** [comment]
From the stack ( SchemaSerializer.getFullState ) it looks like it crashes when somebody joins and the full state is sent. 
The project is pretty big, would be complicated for me to send it to you. I will try to add some debug lines in the framework to understand the issue and report back.

**Comment by dan-merlea** [comment]
Indeed, after changing a bit the assert got that error: `TypeError: Cannot read properties of undefined (reading '$changes')`

**Comment by dan-merlea** [comment]
Added some logs and found the following:

value: undefined
type: <ref *1> [class Spaceship extends Circle]
klass: <ref *1> MapSchema [Map]
field: 303

Can you point me where to look next?

**Comment by dan-merlea** [comment]
New info:

in `'$indexes': Map(360)` I found 2 indexes pointing to the same key. One of them being index 303 pointed out before.

303 => '417',
358 => '417',

**Comment by endel** [comment]
Thanks for investigating so far @dan-merlea. 

The `.allChanges` are a full list of changed fields - they are only encoded when a client first joins the room (in the `.encodeAll()` method). By your description, it looks like the `.allChanges` may be pointing to an item that was already deleted [?]

Deleted items [_should_ have been removed from the `allChanges` list](https://github.com/colyseus/schema/blob/33935b1ef20d054cd10509b44ec19cc12af06242/src/changes/ChangeTree.ts#L292) though. 

This issue is intriguing!

**Comment by dan-merlea** [comment]
Apparently, it was a memory leak in my code. A timer was updating an object that was removed. 
Before understanding the issue, one line that helped me avoid the crash was:

```
if (value == undefined && isMapSchema && operation.op === exports.OPERATION.ADD) continue;
```

added in Schema.ts:533

This line could be added in the base to warn the developer of a possible issue in the code.

**Comment by NakOh** [comment]
I experienced the same issue.

First of all, my cause occurred when the number data entered the key, even though the "Key" of MapSchema was a String.

Even if the type script specified it as a string, the actual data could enter the number.

MapSchema.Need to be modified or warned so that Add is 100% sure that Key must be String.

**Comment by endel** [comment]
Hi there, I'm trying to reproduce this issue on a test scenario, and so far the only way I've managed to do it was by providing a `Number` type for `MapSchema`'s `.set()` methods, as follows:

```typescript
class Player extends Schema {
    @type("number") pos: number = 0;
}

class State extends Schema {
    @type({ map: Player }) players = new MapSchema<Player>();
}

const state = new State();

// @ts-ignore
state.players.set(3, new Player());

state.encodeAll(); // -> "TypeError: Cannot read properties of undefined (reading 'constructor')"
```

Though, TypeScript will fail to compile this as every key in `MapSchema` must be a string instead of a number. (It only compiles if using the `// @ts-ignore` comment as in the example above)

![Screenshot 2023-07-23 at 00 01 30](https://github.com/colyseus/colyseus/assets/130494/bcc1f9a3-2b9b-4f04-81c2-37f5bebae73d)

Can you confirm if this might be the case for you @dan-merlea @NakOh?
(Are you possibly using plain JavaScript? If that's the case, this limitation may not be clear enough)

**Comment by dan-merlea** [comment]
It’s possible! All the keys are numbers and I convert them to string. I’m using typescript, but it’s possible to have missed the conversion somewhere. And being an edge case ( only crashing once a day ) it’s very hard to reproduce. Maybe you can force check the key and crash with info?Or you can just try to convert keys to string. And accept any type of key that implements .toString() ?On 23 Jul 2023, at 06:09, Endel Dreyer ***@***.***> wrote:﻿
Hi there, I'm trying to reproduce this issue on a test scenario, and so far the only way I've managed to do it was by providing a Number type for MapSchema's .set() methods, as follows:
class Player extends Schema {
    @type("number") pos: number = 0;
}

class State extends Schema {
    @type({ map: Player }) players = new MapSchema<Player>();
}

const state = new State();

// @ts-ignore
state.players.set(3, new Player());

state.encodeAll(); // -> "TypeError: Cannot read properties of undefined (reading 'constructor')"
Though, TypeScript will fail to compile this as every key in MapSchema must be a string instead of a number. (It only compiles if using the // @ts-ignore comment as in the example above)

Can you confirm if this might be the case for you @dan-merlea @NakOh?
(Are you possibly using plain JavaScript? If that's the case, this limitation may not be clear enough)

**Comment by endel** [comment]
Thanks for the swift feedback @dan-merlea, I've just released `@colyseus/schema@2.0.11` [forcing MapSchema keys as string](https://github.com/colyseus/schema/commit/e29b4d2c316fd4a16b526ff73a07cf0c07898e6f#diff-82c4c4d0e1ea5723b7350a0f85b404a18671367a9952a3d705a7785bfb81b16e), can you try if that solves the problem for you? 🙏

**Comment by hunkydoryrepair** [comment]
I'm not sure it is related, but in my tests, when `undefined` is set on a property which is an object/schema of its own, it deserializes on the client as `{}` instead of undefined, so it is `truthy` rather than `falsy`, which is unexpected. There doesn't seem to be a really good way to handle undefined properties.

**Comment by 00alia00** [comment]
Hi, landed here after searching for ` TypeError: Cannot read properties of undefined (reading '$changes')`, let me know if you want me to just open a new issue. Anyway, hopefully this helps:

For us, it seems to happen mid to late game when the map is pretty busy (lots of entities), and when someone first joins. The fact that its from GC makes me think it has a size component to the error.

```
colyseus.js:3372 Uncaught TypeError: Cannot read properties of undefined (reading '$changes')
    at colyseus.js:3372:46
    at Set.forEach (<anonymous>)
    at O.garbageCollectDeletedRefs (colyseus.js:3351:34)
    at O.decode (colyseus.js:3727:23)
    at $.patch (colyseus.js:5146:31)
    at $.patch (colyseus.js:4592:29)
    at $.onMessageCallback (colyseus.js:4567:22)
```

**Comment by endel** [comment]
Hi @00alia00, do you think you could isolate/reproduce the issue in a separate environment like this? https://stackblitz.com/edit/colyseus-schema-issue-report cheers 🙏

**Comment by 00alia00** [comment]
unlikely, its a pretty large project with a large schema and we don't have a good repro case.. and when it does happen its with like 13+ players, maybe if once i've narrowed it down I can try.

**Comment by 00alia00** [comment]
Caught it in the debugger once now 
![image](https://github.com/colyseus/colyseus/assets/537506/0143340e-f906-4780-8f07-c57012d34a4e)

**Comment by 00alia00** [comment]
Looks like refCounts gets a NAN from removeRef
![image](https://github.com/colyseus/colyseus/assets/537506/b4dcfebc-5029-49b4-bb46-41d99baefba7)

**Comment by 00alia00** [comment]
maybe something like the following would help track down the issue
```
removeRef(refId: number) {
        const refCount = this.refCounts[refId];
        if (refCount === undefined) {
            console.warn(`trying to remove reference ${refId} that doesn't exist`);
            return;
        }
        if (refCount === 0) {
            console.warn(`trying to remove reference ${refId} with 0 refCount`);
            return;
        }

        this.refCounts[refId] = refCount - 1;
        this.deletedRefs.add(refId);
  }
```

**Comment by endel** [comment]
Thank you for the investigation so far @00alia00, I'm a bit worried that with this fix/workaround we'll never really find out the real reason behind this issue. It sounds like a "remove" operation is coming from server -> client which the client has never received.

If you can share the schema structures and operations (add/remove) that go on in your application - that could help in finding out which operation from the server is causing the issue. 🙏  (you can share privately on my email if you can)

**Comment by tangobeo** [comment]
I have same issue when using reconnect and it's only happen when client reconnect to roomId. Don't know why value is undefined. Is there any chance to fix this?

**Comment by NakOh** [comment]
@tangobeo Check "key" type is "string" is right

**Comment by DivXPro** [comment]
@tangobeo Yes，my issue is same to you, do u found the solution？

**Comment by tangobeo** [comment]
@DivXPro I just ignore the error by adding an if line to encode function:

> 

...
 var fieldIndex = operation.index;
if(changeTree.getType(fieldIndex).name === "EffectV2" && !changeTree.getValue(fieldIndex)) continue;

...
>
with "EffectV2" is name of type got value.contructor undefined. Btw it's a temporary fix.

**Comment by endel** [comment]
There's been a number of iterations on `@colyseus/schema` since this report, so I believe it has been fixed by now. Please feel free to reopen here or open another issue if you'd like to
