### ISSUE TITLE
seat reservation expired on reconnect [re-upload]

### ISSUE THREAD

**Issue by sumin1125** [colyseus/colyseus#571]
Occasionally when reconnecting, a Seat Reservation Expiration error occurs. Please help me how can I solve this problem. The same issue is closed without resolution, so I'm leaving it again.

server code 
```
const presenceOption = process.env.NODE_ENV === 'production' ? {
  host: RD_HOST,
  port: RD_PORT,
  password: RD_PASSWORD
} : {
  host: RD_HOST,
  port: RD_PORT
}

const gameServer = new Server({
  transport,
  // engine: WebSocket.Server,
  // server: server,
  presence: new RedisPresence(
    presenceOption
  ),
  driver: new MongooseDriver(
    MONGO_URI
  )
});
```

server error
`Error: seat reservation expired.
    at uWebSocketsTransport.onConnection (/game-server/game-server-with-node.js/node_modules/@colyseus/uwebsockets-transport/src/uWebSocketsTransport.ts:153:23)
    at open (/game-server/game-server-with-node.js/node_modules/@colyseus/uwebsockets-transport/src/uWebSocketsTransport.ts:78:28)
    at upgrade (/game-server/game-server-with-node.js/node_modules/@colyseus/uwebsockets-transport/src/uWebSocketsTransport.ts:58:21)`

ubuntu - 20.04
colyseus - 0.14
nodejs - v16.19.1
redis server - azure redis cluster

**Comment by endel** [comment]
Need full reproduction scenario, you may be misusing `allowReconnection`.

PS: version 0.14 is not going to receive patches
