### ISSUE TITLE
[Bug]: Transport does not default to ws

### ISSUE THREAD

**Issue by Bogden** [colyseus/colyseus#579]
### Bug description

When running `npm run start` while trying to migrate from 0.14 to 0.15, ran into this:

```
Error: Please provide a 'transport' layer. Default transport not set.
    at Object.getDefaultTransport (@colyseus\tools\node_modules\@colyseus\core\build\Server.js:153:11)
    at getTransport (@colyseus\tools\build\index.js:138:29)
    at listen (@colyseus\tools\build\index.js:111:27)
    at Object.<anonymous> (D:\development\Creo\metabollica\src\index.ts:15:7)
    at Module._compile (node:internal/modules/cjs/loader:1155:14)
    at Module._compile (source-map-support\source-map-support.js:568:25)
    at Module.m._compile (ts-node-dev-hook-25968057576696135.js:69:33)
    at Module._extensions..js (node:internal/modules/cjs/loader:1209:10)
    at require.extensions..jsx.require.extensions..js (ts-node-dev-hook-25968057576696135.js:114:20)
    at require.extensions.<computed> (ts-node-dev-hook-25968057576696135.js:71:20)
[ERROR] 22:46:15 Error: Please provide a 'transport' layer. Default transport not set.
```

Was able to get past it by explicitly providing this in my app.config.ts
```ts
  initializeTransport: function(opts) {
    return new WebSocketTransport({
      ...opts,
      pingInterval: 6000,
      pingMaxRetries: 4,
    });
  },
```

### Steps to reproduce

1. Start a server without initializeTransport or server constructor set
2. Observe the error

### Environment & Versions

Colyseus 0.15.0
Node 16.18.0
Windows 10

**Comment by Bogden** [comment]
Ran into some other issues, I think it's because my package.json still had old version of @colyseus/monitor @colyseus/loadtest, @colyseus/testing or something...

**Comment by endel** [comment]
Hi @tokdaniel, can you open a new issue with a reproduction scenario? Thanks
