### ISSUE TITLE
[Bug]: Scalability falls on Seat Reservation Expired

### ISSUE THREAD

**Issue by eniomarcosm** [colyseus/colyseus#631]
### Context

I always fall into "seat reservation failed" when doing load test running scalability. 

I have configured scalability following the documentation. Here is my code for creating server (consider site_url as my public url):

I always fall into "seat reservation failed" when doing load test running scalability. 

I have configured scalability following the documentation. Here is my code for creating server (consider site_url as my public url):

`
import Arena from "@colyseus/arena";
import { monitor } from "@colyseus/monitor";
import { RedisDriver, RedisPresence } from "colyseus";
import { WebSocketTransport } from "@colyseus/ws-transport"

/**
 * Import your Room files
 */
import { BasicRoom } from "./rooms/BasicRoom";

const nodeAppInstance = Number(process.env.NODE_APP_INSTANCE);

export default Arena({
    getId: () => "SpaceTo colyseus app",
     initializeTransport: function(opts) {
      return new WebSocketTransport({
        ...opts,
        pingInterval: 6000,
        pingMaxRetries: 4,
      });
    },
      options: {
      presence: new RedisPresence(),
      driver: new RedisDriver(),
      publicAddress: "site_url-"+nodeAppInstance,
    },

    initializeGameServer: (gameServer) => {
        gameServer.define('Lobby', BasicRoom);
        gameServer.define('Gallery', BasicRoom);
        gameServer.define('NetworkingArea', BasicRoom);
        gameServer.define('Marketplace', BasicRoom);
    },

    initializeExpress: (app) => {
        app.get("/", (req, res) => {
            res.send("Colyseus server initialized");
        });

        app.use("/colyseus", monitor());
    },

    beforeListen: () => {}
});`

### Bug description

PM2 Log:
/home/ecs-user/.pm2/logs/colyseus-app-multi-error-8.log last 15 lines:
8|colyseus | 2023-09-22T00:26:39:     at Server.upgrade (/home/ecs-user/projects/demospace-scalability/demospace-colyseus-servers/node_modules/ws/lib/websocket-server.js:107:16)
8|colyseus | 2023-09-22T00:26:39:     at Server.emit (node:events:514:28)
8|colyseus | 2023-09-22T00:26:39:     at Server.<anonymous> (/usr/lib/node_modules/pm2/node_modules/@pm2/io/build/main/metrics/httpMetrics.js:152:37)
8|colyseus | 2023-09-22T00:26:39:     at onParserExecuteCommon (node:_http_server:915:14)
8|colyseus | 2023-09-22T00:26:39:     at onParserExecute (node:_http_server:809:3)
8|colyseus | 2023-09-22T00:26:41: Error: seat reservation expired.
8|colyseus | 2023-09-22T00:26:41:     at WebSocketServer.onConnection (/home/ecs-user/projects/demospace-scalability/demospace-colyseus-servers/node_modules/@colyseus/ws-transport/build/WebSocketTransport.js:102:15)

Loadtest
![image](https://github.com/colyseus/colyseus/assets/45578804/b17b2e6a-a914-440e-930f-34515a337c29)

Nginx config:

### Reproduction

My nginx config:

### Steps to reproduce

load test to the server:

`npx` tsx loadtest/load.ts --room NetworkingArea --numClients 50 --endpoint https://site_url-1`

### Environment & Versions

Colyseus version: ^0.15.7
Nodejs: v18.17.0.
TypeScript Version: v10.9.1
Ubuntu: 22.04.2 LTS x86_64

**Comment by endel** [comment]
Hi @eniomarcosm, the `@colyseus/arena` module and version `0.15` will cause conflicts and make the framework not behave properly.

See migration guide [from 0.14 to 0.15 here](https://docs.colyseus.io/migrating/0.15/#colyseusarena-has-been-renamed-to-colyseustools).

The recommended way to scale on 0.15 is now by configuring `publicAddress` and making each Node.js process available publicly. You can find more info about it https://github.com/orgs/colyseus/discussions/578#discussioncomment-6174564

**Comment by eniomarcosm** [comment]
> Hi @eniomarcosm, the `@colyseus/arena` module and version `0.15` will cause conflicts and make the framework not behave properly.
> 
> See migration guide [from 0.14 to 0.15 here](https://docs.colyseus.io/migrating/0.15/#colyseusarena-has-been-renamed-to-colyseustools).
> 
> The recommended way to scale on 0.15 is now by configuring `publicAddress` and making each Node.js process available publicly. You can find more info about it https://github.com/orgs/colyseus/discussions/578#discussioncomment-6174564

Same happens with the official version, same configs:

import config from "@colyseus/tools";
import { monitor } from "@colyseus/monitor";
import { playground } from "@colyseus/playground";
import { RedisDriver, RedisPresence } from "colyseus";
import { WebSocketTransport } from "@colyseus/ws-transport"


/**
 * Import your Room files
 */
import { MyRoom } from "./rooms/MyRoom";


const nodeAppInstance = Number(process.env.NODE_APP_INSTANCE);

export default config({

    initializeGameServer: (gameServer) => {
        /**
         * Define your room handlers:
         */
        gameServer.define('my_room', MyRoom);

    },

  options: {
       presence: new RedisPresence(),
       driver: new RedisDriver(),
       publicAddress: `metakit-backend.spaceto.io/colyseus-${nodeAppInstance}`,
    },

   initializeTransport: function(opts) {
    return new WebSocketTransport({
     ...opts,
      pingInterval: 6000,
      pingMaxRetries: 4,
    });
  },

    initializeExpress: (app) => {
        /**
         * Bind your custom express routes here:
         * Read more: https://expressjs.com/en/starter/basic-routing.html
         */
        app.get("/hello_world", (req, res) => {
            res.send("It's time to kick ass and chew bubblegum!");
        });

        /**
         * Use @colyseus/playground
         * (It is not recommended to expose this route in a production environment)
         */
        if (process.env.NODE_ENV !== "production") {
            app.use("/", playground);
        }

        /**
         * Use @colyseus/monitor
         * It is recommended to protect this route with a password
         * Read more: https://docs.colyseus.io/tools/monitor/#restrict-access-to-the-panel-using-a-password
         */
        app.use("/colyseus", monitor());
    },


    beforeListen: () => {
        /**
         * Before before gameServer.listen() is called.
         */
    }
});

**Comment by drexample** [comment]
@eniomarcosm @endel We're experiencing the same problem - could this issue be reopened?
