### ISSUE TITLE
[Bug]: [ERROR] TypeError: Cannot read properties of undefined (reading 'hgetall')

### ISSUE THREAD

**Issue by akroshteotia** [colyseus/colyseus#636]
### Bug description

While defining the room in arena.config and calling the matchmaker to start room automatically on server creating issue after updating to latest version 

```
import { matchMaker } from "colyseus";
initializeGameServer: (gameServer) => {
  gameServer.define("tournament", TournamentRoom);
  matchMaker.createRoom("tournament", {})
};
```

[ERROR] 12:23:06 TypeError: Cannot read properties of undefined (reading 'hgetall')
 [error] : 2023-10-06 12:23:06 :  uncaughtException: Cannot read properties of undefined (reading 'hgetall')
 TypeError: Cannot read properties of undefined (reading 'hgetall')
     at Object.createRoom (\node_modules\colyseus\node_modules\@colyseus\core\build\MatchMaker.js:204:50)
at Object.initializeGameServer (\src\arena.config.ts:49:20)
  at listen (\node_modules\@colyseus\arena\src\index.ts:87:39)
  at processTicksAndRejections (node:internal/process/task_queues:95:5)

TypeError: Cannot read properties of undefined (reading 'hgetall')
    at Object.createRoom (\node_modules\colyseus\node_modules\@colyseus\core\build\MatchMaker.js:204:50)
   at Object.initializeGameServer (\server\src\arena.config.ts:49:20)
    at listen (\server\node_modules\@colyseus\arena\src\index.ts:87:39)
   at processTicksAndRejections (node:internal/process/task_queues:95:5)

### Reproduction

Create a room and try to start it will matchmaker at server end.

### Steps to reproduce

1.Initialize the server
2. Define the room
3. Create room with Match Maker API

### Environment & Versions

```
"colyseus": "^0.15.9",
"colyseus.js": "^0.15.14",
"@colyseus/arena": "^0.14.24",
"@colyseus/monitor": "^0.15.1",
"@colyseus/schema": "^2.0.16",
"@colyseus/uwebsockets-transport": "^0.15.2",
"uwebsockets-express": "^1.3.4",
"typescript": "^4.9.5",
node -v18.18.0
windows 11
```

**Comment by endel** [comment]
Hi @akroshteotia, the `@colyseus/arena` package has been deprecated in 0.15 in favor of `@colyseus/tools`, please have a look at the 0.14 -> 0.15 migration guide: https://docs.colyseus.io/migrating/0.15/#colyseusarena-has-been-renamed-to-colyseustools

Cheers
