### ISSUE TITLE
[Bug]: TypeError: Cannot read properties of undefined (reading 'types')

### ISSUE THREAD

**Issue by ant-on-elephants** [colyseus/colyseus#640]
### Context

This bug appears after joining the room

### Bug description

This bug appears after joining the room

TypeError: Cannot read properties of undefined (reading 'types')
    at Function.Reflection.encode (D:\typescript-project\BarrageGameServer\node_modules\@colyseus\schema\src\Reflection.ts:88:47)
    at SchemaSerializer.handshake (D:\typescript-project\BarrageGameServer\node_modules\@colyseus\core\build\serializer\SchemaSerializer.js:83:68)
    at OnlineRoom._onJoin (D:\typescript-project\BarrageGameServer\node_modules\@colyseus\core\build\Room.js:327:54)
    at uWebSocketsTransport.onConnection (D:\typescript-project\BarrageGameServer\node_modules\@colyseus\uwebsockets-transport\build\uWebSocketsTransport.js:131:7)
    at open (D:\typescript-project\BarrageGameServer\node_modules\@colyseus\uwebsockets-transport\build\uWebSocketsTransport.js:74:9)
    
![image](https://github.com/colyseus/colyseus/assets/45985016/b97dcd11-1d89-47ff-b0d9-7d01f9437fc9)

### Steps to reproduce

after joining the room

### Environment & Versions

Colyseus version: 0.15.0
Node.js version: 16.15.1
TypeScript version: ...
Operating system: windows

**Comment by ant-on-elephants** [comment]
> Hi @ant-on-elephants, this is the first time I see this error. Can you provide a small reproduction scenario?
> 
> You copy & paste your schema structures on this online environment, and run `npm start` from their terminal to try to reproduce it: https://stackblitz.com/edit/colyseus-schema-issue-report?file=index.ts
> 
> Need to make sure you're using `Reflection.encode()`/`Reflection.decode()`, as per stack trace the issue seems to be in `Reflection`.
> 
> Cheers

Hi, i'm not state. Here are screenshot of state.
![image](https://github.com/colyseus/colyseus/assets/45985016/f3cb75f2-842f-40cf-ac3d-877db2368dea)

This is onlineRoom screenshot of state.
![image](https://github.com/colyseus/colyseus/assets/45985016/97b61f29-5785-4214-9f38-c603bf1db554)

![image](https://github.com/colyseus/colyseus/assets/45985016/0a84f4e7-71eb-4837-9efd-eecc88244eff)

This is account login screenshor of state.
![image](https://github.com/colyseus/colyseus/assets/45985016/6624b86f-1b24-42f8-a0ac-7fe5a1753cd2)

**Comment by endel** [comment]
That's an interesting find, thanks for reporting. 

The root state (`OnlineRoomState`) needs to have at least one field in order not to crash:

```typescript
import { Schema, type } from "@colyseus/schema";

export class OnlineRoomState extends Schema {
  @type("number") atLeastOnePropertyIsRequiredHere: number;
}
```

If you'd rather now use any state, you can also remove the `.setState(new OnlineRoomState())`, which should also fix this issue.

Cheers!

**Comment by ant-on-elephants** [comment]
> That's an interesting find, thanks for reporting.
> 
> The root state (`OnlineRoomState`) needs to have at least one field in order not to crash:
> 
> ```ts
> import { Schema, type } from "@colyseus/schema";
> 
> export class OnlineRoomState extends Schema {
>   @type("number") atLeastOnePropertyIsRequiredHere: number;
> }
> ```
> 
> If you'd rather not use a synchronized state, you can also remove the `.setState(new OnlineRoomState())`, which should also fix this issue.
> 
> Cheers!

**Comment by endel** [comment]
Let's keep this open. Would be best to allow empty states without crashing.

**Comment by ant-on-elephants** [comment]
> > That's an interesting find, thanks for reporting.
> > The root state (`OnlineRoomState`) needs to have at least one field in order not to crash:
> > ```
> > import { Schema, type } from "@colyseus/schema";
> > 
> > export class OnlineRoomState extends Schema {
> >   @type("number") atLeastOnePropertyIsRequiredHere: number;
> > }
> > ```
> > 
> > 
> > If you'd rather not use a synchronized state, you can also remove the `.setState(new OnlineRoomState())`, which should also fix this issue.
> > Cheers!

Thanks!  I remove the `.setState(new OnlineRoomState())`. It worked!!! Thank you.
