### ISSUE TITLE
[Feedback] Authentication - @colyseus/auth

### ISSUE THREAD

**Issue by endel** [colyseus/colyseus#660]
### Context & Description

This thread should be used for general feedback for the new `@colyseus/auth` module (https://github.com/colyseus/colyseus/pull/657, https://github.com/colyseus/colyseus.js/pull/133)

### Use cases

x

### Proposed API

x

**Comment by endel** [comment]
Hi @SleepingProgrammer, thanks for checking out! 

The `@colyseus/auth` needs a preview version of `@colyseus/core`, you can force to use the preview version by adding this to your `package.json`:

```
  "overrides": {
    "@colyseus/core": "preview"
  },
```

Soon the `preview` version will be incorporated on `0.15.x`

**Comment by endel** [comment]
Final release notes are out 🎉  https://github.com/colyseus/colyseus/releases/tag/0.15.15

**Comment by SleepingProgrammer** [comment]
Thanks for letting me know and happy new year! 

I haven't had the time to try out your earlier suggestion, does that mean I can just force colyseus/core to use 0.15.15?

**Comment by endel** [comment]
Hi @SleepingProgrammer, yes 🙌 
Happy New Year ✨🍾

**Comment by JeromeGill** [comment]
https://docs.colyseus.io/authentication/module/#onfinduserbyemail-setting

What is the expected behavior if a user isn't found? are you supposed to throw an error yourself ?

I think the documentation needs to reflect this

Presumably the colysesus db package throws the error internally somewhere here https://github.com/colyseus/webgame-template/blob/main/packages/backend/src/config/auth.ts#L10

**Comment by endel** [comment]
Hi @JeromeGill, thank you for the feedback.

There was a bug getting the return value from `onFindUserByEmail` at the login route - if `null` or `undefined` are returned, the `invalid_credentials` error should've been thrown. I just [fixed this here](https://github.com/colyseus/colyseus/commit/2f7a61777775ff337cc642aa890b3e3739be6016). 

You may customize the error by throwing a different one inside `onFindUserByEmail` too, updated the docs to clarify this behaviour here 🙌  https://docs.colyseus.io/authentication/module/#onfinduserbyemail-setting

**Comment by hunkydoryrepair** [comment]
I'm a little concerned about the change to make `onAuth` static.
We do a lot of checks in onAuth that are specific to the room. Since each room is unique, but all share the same class, we need to know WHICH room they are in, and the static `onAuth` doesn't even appear to provide the `options` where we might determine which room is GOING to be created.

Also, we use the `request` passed in to get the IP address of the player, and then we need to SAVE it on the `client.userData` or in the options (I don't remember which). Using a static onAuth doesn't appear to provide a good way to do that. We could still get the IP address, but then associating it with the player during onJoin, is it possible?

I can see having a static onAuth being useful for optimizations, but deprecating the existing version creates some problems. We could still do a lot of it in onJoin, possibly, except we don't get the `request` in onJoin, so we can't get IP address.

**Comment by hunkydoryrepair** [comment]
Just, for example what we pass to our onAuth and use from the client:

- sessionKey from our authentication process (using Stytch)
- The version number of the client, to determine if they need to refresh the client to get latest version.
- A "captcha" string, so we can validate they are human.
- A telemetry string for fingerprinting
- A timestamp of when they validated, which is used in conjuction with our mapId (room indicator) to make sure they were validated for the given room and have not joined other rooms since being validated.
- A room/map identifier, which is needed to select or create the room, but we also used in conjuction with the timestamp above.
- A world number, for rooms where we allow duplication. We check validity and have some restrictions based on who the player is to access different world numbers.

We also do a check on the # of players in the room. This is so we can allow ADMIN into the rooms even if they are otherwise full for other players. This works because most of our rooms are "single instance" and we prevent creation of duplicate rooms. We turn people away if they are full, rather than spin up a new instance of the same area. 

Conceivably, I think most of these things can be in onJoin, but we cannot benefit from the static onAuth unless we could access all the options passed in from the client.

**Comment by hungnvbb** [comment]
I expect static onAuth() when return data I can get it on onJoin or onCreate, currently can't get it . What purpose static onAuth () ??? .

**Comment by endel** [comment]
Hi @hungnvbb, the return value from `static onAuth()` should be available in 2 places:

```typescript
onJoin(client, options, auth) {
  console.log(client.auth) // here
  console.log(auth) // here
}
```

Let me know if that works for you

**Comment by hungnvbb** [comment]
```
static async onAuth(token,request) {
    if (!token) return false;
    try {
      const info = await verifyToken(token);
      if (!info) return false;
      return info;
    } catch (e) {
      logger.error(e);
      return false;
    }
  }
```

and in onJoin I printed auth , client.auth  result is undefined .

**Comment by yjeroen** [comment]
Wishlist:

- Ability to configure password requirements
- Ability to add 2FA Authenticator option (e.g. via email and/or an QR-code based 2fa Authenticator app)

**Comment by stuthelotusguy** [comment]
Quick question:  In the auth module there are a few variables for configuring the 'grant' module for oauth (in addProvider),  however some services like auth0 require additional variables like 'subdomain'. How are these provided to the underlying service through the module?

**Comment by endel** [comment]
Hi @stuthelotusguy 👋  I see now that `OAuthProviderConfig` is a bit too strict on the property names, so if you're using TypeScript it will complain "domain" is not allowed, but it should actually work:

```typescript
auth.oauth.addProvider("auth0", {
  // ...
  // @ts-ignore
  domain: "..."
});
```

Let me know if that works for you. Maybe we should add `[key: string]: string` to be more permissive on `OAuthProviderConfig`.

**Comment by stuthelotusguy** [comment]
Yes, that does work to get around the strictness. I agree that more permissive may be a better option long term. Great work BTW.

**Comment by JoaoMPdS** [comment]
I've encountered a little issue while using the client module: when I sign the client out, the "authjs.session-token" persists, therefor on middleware requests, the cookie is also there. Is this intended? Am I supposed to delete the cookie on sign-out?

Any help will be greatly appreciated 😄

**Comment by antonytrupe** [comment]
I'm getting an error when coming back from using the google provider via 
`const client = new Client(BACKEND_URL)`
`client.auth.token = "xxxx"`

`await client.auth.signInWithProvider('google')`

JsonWebTokenError: jwt malformed
    at module.exports [as verify] (.....\node_modules\jsonwebtoken\verify.js:70:17)
    at .....\node_modules\@colyseus\auth\build\JWT.js:52:35
    at new Promise (<anonymous>)
    at Object.verify (C:\Users\anton\Desktop\marble-game\node_modules\@colyseus\auth\build\JWT.js:51:12)
    at .....\node_modules\@colyseus\auth\build\oauth.js:122:56
    at Layer.handle [as handle_request] (.....\node_modules\express\lib\router\layer.js:95:5)
    at next (.....\node_modules\express\lib\router\route.js:149:13)
    at Route.dispatch (.....\node_modules\express\lib\router\route.js:119:3)
    at Layer.handle [as handle_request] (.....\node_modules\express\lib\router\layer.js:95:5)
    at .....\node_modules\express\lib\router\index.js:284:15

The client(phaser/nextjs) is running on a different server then the colyseus server. I suspect that is relevant.
When navigating to colyseusserver/auth/provider/google, it takes me through the whole flow and back to the auth.oauth.onCallback handler successfully.

My first question is am I wrong in thinking its ok to have the client on a different server then the colyseus server and use the auth module?
If I'm not wrong, any idea's what I'm doing wrong?

**Comment by mean-ui-thread** [comment]
Another wish list:

Would be nice to have a way to run `client.auth.signInWithProvider(providerName, settings)` in a nodejs environment instead of a web browser environment. Right now, it is using `window` and `screen` directly in its implementation and crashes when it is called from node, while the other auth functions seem to work just fine in node.

Scenarios where this would be helpful:
- A nodejs command line tool 
- A typescript/javascript video game that uses [node-sdl2](https://www.npmjs.com/package/node-sdl2) or some other game engine.
- etc

**Comment by endel** [comment]
@mean-ui-thread thanks for the feedback! In order to allow communication between the external browser and CLI (or native window via Electron/Tauri/etc), it would require changes both in the JS SDK and the server-side.

The JS SDK (client-side) would need a way to receive data from the browser, a common approach for this is starting a local server (e.g. `http://127.0.0.1:3567`), so the external browser can send a request to it with the user data (server-side) once the OAuth flow has been completed.  Currently it only uses [`window.opener.postMessage()`](https://github.com/colyseus/colyseus/blob/d9b6bf87f8eee1cb2dcc5eba5309a3faeae572e7/packages/auth/src/oauth.ts#L212).

**Comment by icegriffinguru** [comment]
Hello.
"auth/confirm-email" callback from @colyseus/auth package redirects to the url itself after success or failure of confirming email.
It creates a loop of calling "auth/confirm-email" url and I only see a white screen on the browser.
I think it should redirect to another page showing confirmation result.

https://github.com/colyseus/colyseus/blob/1a7da98cbeee551587e6119d06a39a441421827b/packages/auth/src/auth.ts#L273
