### ISSUE TITLE
[Bug]: Map Schema Removing value creates issue

### ISSUE THREAD

**Issue by akroshteotia** [colyseus/colyseus#690]
### Context

Front end JS SDK

### Bug description

Using map schema to track last 5 games in state. For first 5 games it works fine as last 5 game map is empty but after sixth game when i remove a value and add new value in state it gives error

index.js:2313 Uncaught TypeError: Cannot read properties of undefined (reading '$changes')
    at eval (index.js:2313:41)
    at Set.forEach (<anonymous>)
    at ReferenceTracker.garbageCollectDeletedRefs (index.js:2292:30)
    at Schema.decode (index.js:2679:19)
    at SchemaSerializer.patch (SchemaSerializer.js:13:27)
    at Room.patch (Room.js:220:25)
    at Room.onMessageCallback (Room.js:195:18)

### Steps to reproduce

Login at http://3.28.126.178/
U-MA0001
P-1234

go to Manage games and view games 
wait for sometime it will start showing this

### Environment & Versions

"colyseus": "^0.15.9",
Node - v20.10.0
TypeScript - 4.9.5
OS -Ubuntu- v20

**Comment by akroshteotia** [comment]
So i tried some changes to file ./node_module/@colyseus/schema/build/umd/index.js

add if(ref != undefined)  solved the issue in else condition

`// for decoding
        ReferenceTracker.prototype.garbageCollectDeletedRefs = function () {
            var _this = this;
            this.deletedRefs.forEach(function (refId) {
                //
                // Skip active references.
                //
                if (_this.refCounts[refId] > 0) {
                    return;
                }
                var ref = _this.refs.get(refId);
                //
                // Ensure child schema instances have their references removed as well.
                //
                if (ref instanceof Schema) {
                    for (var fieldName in ref['_definition'].schema) {
                        if (typeof (ref['_definition'].schema[fieldName]) !== "string" &&
                            ref[fieldName] &&
                            ref[fieldName]['$changes']) {
                            _this.removeRef(ref[fieldName]['$changes'].refId);
                        }
                    }
                }
                else if(ref != undefined) {
                    var definition = ref['$changes'].parent._definition;
                    var type = definition.schema[definition.fieldsByIndex[ref['$changes'].parentIndex]];
                    if (typeof (Object.values(type)[0]) === "function") {
                        Array.from(ref.values())
                            .forEach(function (child) { return _this.removeRef(child['$changes'].refId); });
                    }
                }
                _this.refs.delete(refId);
                delete _this.refCounts[refId];
            });
            // clear deleted refs.
            this.deletedRefs.clear();
        };
        return ReferenceTracker;`

**Comment by akroshteotia** [comment]
Found same thing in Unity SDK in ReferenceTracker
