### ISSUE TITLE
[Bug]: Playground not working

### ISSUE THREAD

**Issue by hungnvbb** [colyseus/colyseus#720]
### Bug description

When add playground and access I got error like  below
`TypeError: Cannot read properties of undefined (reading 'find')
    at /xxx/node_modules/@colyseus/playground/build/index.js:42:53
    at Layer.handle [as handle_request] (/xxx/node_modules/express/lib/router/layer.js:95:5)
    at next (/xxx/node_modules/express/lib/router/route.js:149:13)
    at Route.dispatch (/xxx/node_modules/express/lib/router/route.js:119:3)
    at Layer.handle [as handle_request] (/xxx/node_modules/express/lib/router/layer.js:95:5)
    at /xxx/node_modules/express/lib/router/index.js:284:15
    at Function.process_params (/xxx/node_modules/express/lib/router/index.js:346:12)
    at next (/xxx/node_modules/express/lib/router/index.js:280:10)
    at SendStream.error (/xxx/node_modules/serve-static/index.js:121:7)
    at SendStream.emit (node:events:517:28)
    at SendStream.error (/xxx/node_modules/send/index.js:270:17)
    at SendStream.onStatError (/xxx/node_modules/send/index.js:417:12)
    at next (/xxx/node_modules/send/index.js:731:16)
    at onstat (/xxx/node_modules/send/index.js:720:14)
    at FSReqCallback.oncomplete (node:fs:210:21)
    at FSReqCallback.callbackTrampoline (node:internal/async_hooks:130:17)`

### Steps to reproduce

This is define playground
![Screenshot 2024-04-20 at 10 55 09](https://github.com/colyseus/colyseus/assets/143471704/12e2cdcf-f93b-4e15-8088-266b7453123e)

### Environment & Versions

colyseus: 0.14.0
node : 18.18.0
 typescript": "5.4.5"
 "@colyseus/playground": "0.15.12"

**Comment by endel** [comment]
Hi @hungnvbb, the playground tool only works with `colyseus` version `0.15+`

**Comment by hungnvbb** [comment]
After upgrade the latest colyseus 0.15.15, still error like that .

**Comment by endel** [comment]
Hi @hungnvbb, can you provide a repository with a way to reproduce it?

**Comment by hungnvbb** [comment]
Hi @endel  , I have fixed this issue by switching from @colyseus/arena to @colyseus/tools. It seems like @colyseus/arena is no longer supported, isn't it?

**Comment by issacclee** [comment]
> Hi @endel , I have fixed this issue by switching from @colyseus/arena to @colyseus/tools. It seems like @colyseus/arena is no longer supported, isn't it?

@colyseus/arena has been deprecated as per the document here https://docs.colyseus.io/migrating/0.15/#colyseusarena-has-been-renamed-to-colyseustools
