### ISSUE TITLE
[Bug]: error thrown in onJoin does not pass error message to client

### ISSUE THREAD

**Issue by devcube9** [colyseus/colyseus#732]
### Bug description

1. Throw an error with a message in a room's onJoin
2. Client's error message is undefined

### Reproduction

[Archive.zip](https://github.com/user-attachments/files/15567128/Archive.zip)

### Steps to reproduce

1. node server.js
2. node client.js

### Environment & Versions

"@colyseus/uwebsockets-transport": "^0.15.7",
"colyseus": "^0.15.17",
"colyseus.js": "^0.15.22"
node: v20.10.0

**Comment by endel** [comment]
Thank you for the repro. This is the error I see from the server, going to investigate soon:

```
Warning: uWS.HttpResponse writes must be made from within a corked callback. See documentation for uWS.HttpResponse.cork and consult the user manual.
Warning: uWS.HttpResponse writes must be made from within a corked callback. See documentation for uWS.HttpResponse.cork and consult the user manual.
Error: error from server
    at GameRoom.onJoin (/Users/endel/Projects/colyseus/clients/colyseus-issue-732/server.js:7:15)
    at GameRoom._onJoin (/Users/endel/Projects/colyseus/clients/colyseus-issue-732/node_modules/@colyseus/core/build/Room.js:338:22)
    at uWebSocketsTransport.onConnection (/Users/endel/Projects/colyseus/clients/colyseus-issue-732/node_modules/@colyseus/uwebsockets-transport/build/uWebSocketsTransport.js:136:18)
    at open (/Users/endel/Projects/colyseus/clients/colyseus-issue-732/node_modules/@colyseus/uwebsockets-transport/build/uWebSocketsTransport.js:76:20)
    at upgrade (/Users/endel/Projects/colyseus/clients/colyseus-issue-732/node_modules/@colyseus/uwebsockets-transport/build/uWebSocketsTransport.js:60:13)
```

**Comment by endel** [comment]
This issue has been fixed now in 0.16 🎉  https://github.com/colyseus/colyseus/releases/tag/0.16.0
