### ISSUE TITLE
[Bug]: Sometimes server auto restart

### ISSUE THREAD

**Issue by ridozito** [colyseus/colyseus#744]
### Bug description

I deployed my application to Colyseus Cloud. Recently, the server sometimes restarts on its own. I found the following error log. What is the cause of this, and can anyone help me?

`0|fafi-gam | 2024-06-24T20:04:21: TypeError: Cannot read properties of undefined (reading 'refId')
0|fafi-gam | 2024-06-24T20:04:21:     at Schema.encode (/home/deploy/source/node_modules/@colyseus/schema/build/cjs/index.js:2832:52)
0|fafi-gam | 2024-06-24T20:04:21:     at SchemaSerializer.applyPatches (/home/deploy/source/node_modules/@colyseus/core/build/serializer/SchemaSerializer.js:51:34)
0|fafi-gam | 2024-06-24T20:04:21:     at GameRoom.broadcastPatch (/home/deploy/source/node_modules/@colyseus/core/build/Room.js:265:41)
0|fafi-gam | 2024-06-24T20:04:21:     at Timeout._onTimeout (/home/deploy/source/node_modules/@colyseus/core/build/Room.js:172:52)
0|fafi-gam | 2024-06-24T20:04:21:     at listOnTimeout (node:internal/timers:573:17)
0|fafi-gam | 2024-06-24T20:04:21:     at process.processTimers (node:internal/timers:514:7)`

### Steps to reproduce

nothing

### Environment & Versions

colyseus version: 0.15.15
nodejs : 20.12.2
typescript: 5.4.5

**Comment by endel** [comment]
Hi @ridozito, this sounds like an internal encoding issue on the server-side. It is very likely certain schema operation is causing the encoder to get into an inconsistent state. I'd like to know more about your scenario to make sure it gets fixed specially as a new schema version is coming out soon. Can you DM me on Discord or email? Thank you

**Comment by ridozito** [comment]
@endel  Sure, I have sent a friend request

**Comment by nmime** [comment]
Error: "refId" not found: 28
    at _.decode (file:///app/node_modules/@colyseus/schema/build/esm/index.mjs:2389:27)
    at SchemaSerializer.patch (file:///app/node_modules/colyseus.js/build/esm/serializer/SchemaSerializer.mjs:13:27)
    at Room.patch (file:///app/node_modules/colyseus.js/build/esm/Room.mjs:200:25)
    at Room.onMessageCallback (file:///app/node_modules/colyseus.js/build/esm/Room.mjs:175:18)
    at callListener (/app/node_modules/colyseus.js/node_modules/ws/lib/event-target.js:290:14)
    at WebSocket.onMessage (/app/node_modules/colyseus.js/node_modules/ws/lib/event-target.js:209:9)
    at WebSocket.emit (node:events:519:28)
    at Receiver.receiverOnMessage (/app/node_modules/colyseus.js/node_modules/ws/lib/websocket.js:1220:20)
    at Receiver.emit (node:events:519:28)
    at Receiver.dataMessage (/app/node_modules/colyseus.js/node_modules/ws/lib/receiver.js:569:14)
Error: "refId" not found: 28
    at _.decode (file:///app/node_modules/@colyseus/schema/build/esm/index.mjs:2389:27)
    at SchemaSerializer.patch (file:///app/node_modules/colyseus.js/build/esm/serializer/SchemaSerializer.mjs:13:27)
    at Room.patch (file:///app/node_modules/colyseus.js/build/esm/Room.mjs:200:25)
    at Room.onMessageCallback (file:///app/node_modules/colyseus.js/build/esm/Room.mjs:175:18)
    at callListener (/app/node_modules/colyseus.js/node_modules/ws/lib/event-target.js:290:14)
    at WebSocket.onMessage (/app/node_modules/colyseus.js/node_modules/ws/lib/event-target.js:209:9)
    at WebSocket.emit (node:events:519:28)
    at Receiver.receiverOnMessage (/app/node_modules/colyseus.js/node_modules/ws/lib/websocket.js:1220:20)
    at Receiver.emit (node:events:519:28)
    at Receiver.dataMessage (/app/node_modules/colyseus.js/node_modules/ws/lib/receiver.js:569:14)
error during shutdown: already_shutting_down


Caught similar error
