### ISSUE TITLE
[Bug]:  Encountered a "TypeError: bytes is not iterable" when processing client join request.

### ISSUE THREAD

**Issue by hosseinmobarakian** [colyseus/colyseus#747]
### Bug description

After user joined i got this error imediately:

```
joined 4fYbUUTf0
TypeError: bytes is not iterable
    at 14 (C:\...\node_modules\@colyseus\core\build\Protocol.js:92:37)
    at MainRoom.sendFullState (C:\...\node_modules\@colyseus\core\build\Room.js:448:91)     
    at MainRoom._onMessage (C:\...\node_modules\@colyseus\core\build\Room.js:567:14)  
```

I'm using colyseus version ^0.15.17. I investigated the TypeError: bytes is not iterable error and found the issue. In the core/build/Protocol.js file, a variable named bytes is always null. This null value is then used in Room.js with the spread operator (...), which causes the error because null cannot be iterated over.

### Steps to reproduce

```
TypeError: bytes is not iterable
    at 14 (C:\...\node_modules\@colyseus\core\build\Protocol.js:92:37)
    at MainRoom.sendFullState (C:\...\node_modules\@colyseus\core\build\Room.js:448:91)     
    at MainRoom._onMessage (C:\...\node_modules\@colyseus\core\build\Room.js:567:14)  
```

### Environment & Versions

colyseus version ^0.15.17

**Comment by endel** [comment]
Hi @hosseinmobarakian, can you please send me the server code where this issue happens so I can investigate? Thanks

**Comment by hosseinmobarakian** [comment]
Sure, this is my Room:

```
interface IMainRoom {
    onlineUsers:number;
    players: Map<number, Client>;
    messages:string[];
}

export default class MainRoom extends Room<IMainRoom> {
    onCreate(options: any): void | Promise<any> {
        this.setState({
            players: new Map(),
            onlineUsers: 0,
            messages: []
        });
        
        this.onMessage(0 , (client, message: any)=>{
            this.state.messages.push(message.message);
        });
    }

    async onJoin(client: Client, options?: any, auth?: this["clients"]): Promise<any> {
        let clientToken = options?.client;
        const clientId = validateInitData(clientToken)?.id;
        if (!clientId) {
            client.leave();
            return;
        }



        this.state.players.set(clientId, client)
        this.state.onlineUsers = this.state.players.size;
        client.send(0 , 'hello')
    }

    onLeave(client: Client, consented?: boolean): void | Promise<any> {
        let findPlayerBySessionId = [...this.state.players.entries()]
            .filter(({ 1: player }) => player.sessionId === client.sessionId)
            .map(([k]) => k);

        if (findPlayerBySessionId[0]) {
            this.state.players.delete(findPlayerBySessionId[0]);
            this.state.onlineUsers = this.state.players.size;
        }
    }

}
```

**Comment by endel** [comment]
I see - it is required to define your state structure as a class with `@type()` decorators… I like the way you did it though 🤔

```typescript
import { Schema, type } from “@colyseus/schema”;

class MyState extends Schema {
  @type({map: Player}) players = new MapSchema<Player>();
```

See docs here: https://docs.colyseus.io/state/schema/
